namespace AltomateHR.Api.Modules.Payroll;

// Demonym → ISO 3166-1 alpha-2 country code.
//
// The LHDN CP39 / e-Data PCB detail record carries a 2-character country code
// at positions 109-110, beside a foreign employee's passport number. Nothing on
// the profile holds one, so the field went out blank for every foreign
// employee. The nationality already names the country, so this derives the code
// rather than adding a field an admin would have to fill twice.
//
// Ported from the legacy system's lib/nationality-country-codes.ts, keyed on
// the same 179 demonyms its nationality dropdown offers. Matched
// case-insensitively because v2 stores nationality as free text rather than a
// picked option, so "malaysian" must resolve the same as "Malaysian".
//
// An unmapped or missing nationality returns "", and the renderer leaves the
// field blank — the behaviour before this map existed.
//
// LHDN publishes its own country-code table. It has followed ISO alpha-2 in
// every case checked so far, but a rejection naming the country code is a sign
// to verify that entry against their list rather than to assume this is right.
public static class NationalityCountryCodes
{
    private static readonly Dictionary<string, string> ByDemonym =
        new(StringComparer.OrdinalIgnoreCase)
    {
        ["Malaysian"] = "MY",
        ["Afghan"] = "AF",
        ["Albanian"] = "AL",
        ["Algerian"] = "DZ",
        ["American"] = "US",
        ["Andorran"] = "AD",
        ["Angolan"] = "AO",
        ["Argentine"] = "AR",
        ["Armenian"] = "AM",
        ["Australian"] = "AU",
        ["Austrian"] = "AT",
        ["Azerbaijani"] = "AZ",
        ["Bahamian"] = "BS",
        ["Bahraini"] = "BH",
        ["Bangladeshi"] = "BD",
        ["Barbadian"] = "BB",
        ["Belarusian"] = "BY",
        ["Belgian"] = "BE",
        ["Belizean"] = "BZ",
        ["Beninese"] = "BJ",
        ["Bhutanese"] = "BT",
        ["Bolivian"] = "BO",
        ["Bosnian"] = "BA",
        ["Botswanan"] = "BW",
        ["Brazilian"] = "BR",
        ["British"] = "GB",
        ["Bruneian"] = "BN",
        ["Bulgarian"] = "BG",
        ["Burkinabe"] = "BF",
        ["Burmese"] = "MM",
        ["Burundian"] = "BI",
        ["Cambodian"] = "KH",
        ["Cameroonian"] = "CM",
        ["Canadian"] = "CA",
        ["Cape Verdean"] = "CV",
        ["Central African"] = "CF",
        ["Chadian"] = "TD",
        ["Chilean"] = "CL",
        ["Chinese"] = "CN",
        ["Colombian"] = "CO",
        ["Comoran"] = "KM",
        ["Congolese"] = "CG",
        ["Costa Rican"] = "CR",
        ["Croatian"] = "HR",
        ["Cuban"] = "CU",
        ["Cypriot"] = "CY",
        ["Czech"] = "CZ",
        ["Danish"] = "DK",
        ["Djiboutian"] = "DJ",
        ["Dominican"] = "DO",
        ["Dutch"] = "NL",
        ["East Timorese"] = "TL",
        ["Ecuadorean"] = "EC",
        ["Egyptian"] = "EG",
        ["Emirati"] = "AE",
        ["Equatorial Guinean"] = "GQ",
        ["Eritrean"] = "ER",
        ["Estonian"] = "EE",
        ["Ethiopian"] = "ET",
        ["Fijian"] = "FJ",
        ["Filipino"] = "PH",
        ["Finnish"] = "FI",
        ["French"] = "FR",
        ["Gabonese"] = "GA",
        ["Gambian"] = "GM",
        ["Georgian"] = "GE",
        ["German"] = "DE",
        ["Ghanaian"] = "GH",
        ["Greek"] = "GR",
        ["Grenadian"] = "GD",
        ["Guatemalan"] = "GT",
        ["Guinean"] = "GN",
        ["Guyanese"] = "GY",
        ["Haitian"] = "HT",
        ["Honduran"] = "HN",
        ["Hong Konger"] = "HK",
        ["Hungarian"] = "HU",
        ["Icelandic"] = "IS",
        ["Indian"] = "IN",
        ["Indonesian"] = "ID",
        ["Iranian"] = "IR",
        ["Iraqi"] = "IQ",
        ["Irish"] = "IE",
        ["Israeli"] = "IL",
        ["Italian"] = "IT",
        ["Ivorian"] = "CI",
        ["Jamaican"] = "JM",
        ["Japanese"] = "JP",
        ["Jordanian"] = "JO",
        ["Kazakh"] = "KZ",
        ["Kenyan"] = "KE",
        ["Kuwaiti"] = "KW",
        ["Kyrgyz"] = "KG",
        ["Lao"] = "LA",
        ["Latvian"] = "LV",
        ["Lebanese"] = "LB",
        ["Liberian"] = "LR",
        ["Libyan"] = "LY",
        ["Liechtensteiner"] = "LI",
        ["Lithuanian"] = "LT",
        ["Luxembourger"] = "LU",
        ["Macanese"] = "MO",
        ["Macedonian"] = "MK",
        ["Malagasy"] = "MG",
        ["Malawian"] = "MW",
        ["Maldivian"] = "MV",
        ["Malian"] = "ML",
        ["Maltese"] = "MT",
        ["Mauritanian"] = "MR",
        ["Mauritian"] = "MU",
        ["Mexican"] = "MX",
        ["Moldovan"] = "MD",
        ["Monegasque"] = "MC",
        ["Mongolian"] = "MN",
        ["Montenegrin"] = "ME",
        ["Moroccan"] = "MA",
        ["Mozambican"] = "MZ",
        ["Namibian"] = "NA",
        ["Nepali"] = "NP",
        ["New Zealander"] = "NZ",
        ["Nicaraguan"] = "NI",
        ["Nigerian"] = "NG",
        ["Nigerien"] = "NE",
        ["North Korean"] = "KP",
        ["Norwegian"] = "NO",
        ["Omani"] = "OM",
        ["Pakistani"] = "PK",
        ["Palestinian"] = "PS",
        ["Panamanian"] = "PA",
        ["Papua New Guinean"] = "PG",
        ["Paraguayan"] = "PY",
        ["Peruvian"] = "PE",
        ["Polish"] = "PL",
        ["Portuguese"] = "PT",
        ["Qatari"] = "QA",
        ["Romanian"] = "RO",
        ["Russian"] = "RU",
        ["Rwandan"] = "RW",
        ["Salvadoran"] = "SV",
        ["Samoan"] = "WS",
        ["Saudi"] = "SA",
        ["Senegalese"] = "SN",
        ["Serbian"] = "RS",
        ["Seychellois"] = "SC",
        ["Sierra Leonean"] = "SL",
        ["Singaporean"] = "SG",
        ["Slovak"] = "SK",
        ["Slovenian"] = "SI",
        ["Somali"] = "SO",
        ["South African"] = "ZA",
        ["South Korean"] = "KR",
        ["South Sudanese"] = "SS",
        ["Spanish"] = "ES",
        ["Sri Lankan"] = "LK",
        ["Sudanese"] = "SD",
        ["Surinamese"] = "SR",
        ["Swazi"] = "SZ",
        ["Swedish"] = "SE",
        ["Swiss"] = "CH",
        ["Syrian"] = "SY",
        ["Taiwanese"] = "TW",
        ["Tajik"] = "TJ",
        ["Tanzanian"] = "TZ",
        ["Thai"] = "TH",
        ["Togolese"] = "TG",
        ["Tongan"] = "TO",
        ["Trinidadian"] = "TT",
        ["Tunisian"] = "TN",
        ["Turkish"] = "TR",
        ["Turkmen"] = "TM",
        ["Ugandan"] = "UG",
        ["Ukrainian"] = "UA",
        ["Uruguayan"] = "UY",
        ["Uzbek"] = "UZ",
        ["Venezuelan"] = "VE",
        ["Vietnamese"] = "VN",
        ["Yemeni"] = "YE",
        ["Zambian"] = "ZM",
        ["Zimbabwean"] = "ZW",
    };

    // The 179 demonyms, as spelled on the dropdown. Nationalities resolves
    // free text onto these.
    public static IEnumerable<string> Demonyms => ByDemonym.Keys;

    public static string ForNationality(string? nationality)
    {
        var key = nationality?.Trim();
        if (string.IsNullOrEmpty(key)) return string.Empty;
        return ByDemonym.TryGetValue(key, out var code) ? code : string.Empty;
    }
}
