using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using static AltomateHR.Api.Modules.LhdnForms.Pdf.LhdnPdfShared;

namespace AltomateHR.Api.Modules.LhdnForms.Pdf;

// PCB 2(II) — Statement of Payment by Employer (Pin. 2012). On-request MTD
// allocation statement: any employee, any year. The monthly table is the
// whole point of the form; every month is blank until this app has a
// payroll-run engine to source MTD/CP38 figures from.
public static class Pcb2IiPdf
{
    public static byte[] Render(LhdnFormPayload p) =>
        Document.Create(doc => doc.Page(page =>
        {
            Frame(page);
            page.Header().Element(h => Header(h, p));
            page.Content().Element(c => Body(c, p));
            page.Footer().Element(f => Footer(f, "PCB 2(II)", p.Employer.EmployerName ?? p.OrganizationName, p.Employee.Name));
        })).GeneratePdf();

    private static void Header(IContainer container, LhdnFormPayload p) =>
        container.Column(col =>
        {
            col.Item().Element(c => BrandHeader(c, p, "PCB 2(II)", "Pin. 2012"));
            col.Item().Element(c => TitleBlock(c,
                "STATEMENT OF PAYMENT BY EMPLOYER",
                "Penyata Pembayaran Oleh Majikan",
                $"Tax Deduction Made During The Year {p.Year}"));
        });

    private static void Body(IContainer container, LhdnFormPayload p) =>
        container.Column(col =>
        {
            var e = p.Employee;

            col.Item().Text(t =>
            {
                t.DefaultTextStyle(s => s.FontSize(9).LineHeight(1.5f));
                t.Line("To: Chief Executive Officer / Director General Inland Revenue");
                t.Line("Inland Revenue Board Of Malaysia");
                t.Line($"Branch: ____________________________________   Date: {FmtDate(p.GeneratedAt)}");
            });

            col.Item().Element(c => SectionHeader(c, "1. Employee Identification"));
            col.Item().Element(c => KvRow(c, "Name of Employee / Nama Pekerja", e.Name));
            col.Item().Element(c => KvRow(c, "New Identity Card No. / Passport No.", e.IdNumber));
            col.Item().Element(c => KvRow(c, "Employee Income Tax No. (TIN)", e.IncomeTaxNumber));
            col.Item().Element(c => KvRow(c, "Staff No.", e.EmployeeCode));
            col.Item().Element(c => KvRow(c, "Employer's No. (E)", p.Employer.EmployerTin));

            col.Item().Element(c => SectionHeader(c, $"2. Deductions Made During The Year {p.Year}"));
            if (!p.HasPayrollHistory) col.Item().Element(PayrollHistoryDisclaimer);
            col.Item().Element(c => MonthlyTable(c, p));

            col.Item().Element(c => SectionHeader(c, $"3. Deductions for Preceding-Year Income Paid In {p.Year}"));
            col.Item().PaddingBottom(4).Text(
                $"Fill in by hand if any preceding-year income was paid out (e.g. arrears, late bonus) in {p.Year}. " +
                "AltomateHR does not track these separately from the current-year run.")
                .FontSize(8.5f).FontColor("#64748b");
            col.Item().Element(PreceedingYearTable);

            col.Item().Element(c => SignatureBlock(c,
                left:
                [
                    ("Name of Officer:", p.Employer.DeclarantName),
                    ("Designation:", p.Employer.DeclarantPosition),
                    ("Telephone No.:", p.Employer.Phone),
                ],
                right:
                [
                    ("Name and Address of Employer:", p.Employer.EmployerName ?? p.OrganizationName),
                    ("", p.Employer.FullAddress),
                ]));

            col.Item().Element(c => ClosingNote(c,
                $"Generated by AltomateHR on {FmtDate(p.GeneratedAt)}. This summary is a working document — " +
                "transcribe the values onto the official LHDN PCB 2(II) form before submission. Receipt / bank-slip " +
                "numbers can be filled in by hand once the underlying MTD payment has cleared."));
        });

    private static void MonthlyTable(IContainer container, LhdnFormPayload p) =>
        container.Table(table =>
        {
            table.ColumnsDefinition(c =>
            {
                c.RelativeColumn(1.5f);  // Month
                c.RelativeColumn(1.4f);  // MTD
                c.RelativeColumn(1.4f);  // CP38
                c.RelativeColumn(2);     // Receipt / Bank Slip No.
                c.RelativeColumn(1.5f);  // Receipt Date
            });

            table.Header(h =>
            {
                HeadCell(h, "Month");
                HeadCell(h, "MTD (RM)", right: true);
                HeadCell(h, "CP38 (RM)", right: true);
                HeadCell(h, "Receipt / Bank Slip No.");
                HeadCell(h, "Receipt Date");
            });

            decimal totalMtd = 0, totalCp38 = 0;
            for (var i = 0; i < 12; i++)
            {
                var m = p.PerMonth[i];
                totalMtd += m?.Mtd ?? 0;
                totalCp38 += m?.Cp38 ?? 0;
                Row(table).Text(MonthNames[i]).FontSize(8.5f);
                Row(table).AlignRight().Text(m is null ? "" : FmtRm(m.Mtd)).FontSize(8.5f);
                Row(table).AlignRight().Text(m is null ? "" : FmtRm(m.Cp38)).FontSize(8.5f);
                Row(table).Text("").FontSize(8.5f);
                Row(table).Text("").FontSize(8.5f);
            }

            TotalRow(table).Text("Total").FontSize(9).Bold();
            TotalRow(table).AlignRight().Text(FmtRm(totalMtd)).FontSize(9).Bold();
            TotalRow(table).AlignRight().Text(FmtRm(totalCp38)).FontSize(9).Bold();
            TotalRow(table).Text("").FontSize(9);
            TotalRow(table).Text("").FontSize(9);
        });

    private static void PreceedingYearTable(IContainer container) =>
        container.Table(table =>
        {
            table.ColumnsDefinition(c =>
            {
                c.RelativeColumn(1.5f);
                c.RelativeColumn(1);
                c.RelativeColumn(1);
                c.RelativeColumn(1.2f);
                c.RelativeColumn(1.5f);
            });
            table.Header(h =>
            {
                HeadCell(h, "Type of Income");
                HeadCell(h, "Month");
                HeadCell(h, "Year");
                HeadCell(h, "MTD (RM)", right: true);
                HeadCell(h, "Receipt / Slip No.");
            });
            for (var i = 0; i < 3; i++)
                for (var col = 0; col < 5; col++)
                    Row(table).Text("").FontSize(8.5f);
        });

    private static IContainer HeadCell(TableCellDescriptor h, string text, bool right = false)
    {
        var cell = h.Cell().Background("#f8fafc").PaddingVertical(4).PaddingHorizontal(3).BorderBottom(1).BorderColor("#cbd5e1");
        var aligned = right ? cell.AlignRight() : cell;
        aligned.Text(text).FontSize(8.5f).Bold();
        return cell;
    }

    private static IContainer Row(TableDescriptor t) =>
        t.Cell().BorderBottom(0.5f).BorderColor("#e2e8f0").PaddingVertical(3).PaddingHorizontal(3);

    private static IContainer TotalRow(TableDescriptor t) =>
        t.Cell().BorderTop(1).BorderColor("#0f172a").PaddingVertical(4).PaddingHorizontal(3);
}
